SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE GRUPO_ROTINAS DISABLE ALL TRIGGERS')
INSERT INTO GRUPO_ROTINAS
(DESCRICAO, GRUPO, INIBE_ACIONAMENTO, SIS)
SELECT * FROM (
SELECT DESCRICAO,GRUPO,INIBE_ACIONAMENTO,SIS FROM GRUPO_ROTINAS WHERE 1=0 UNION ALL
SELECT 'Grupo de rotinas customizadas que são utilizadas no Ergon NG', 'RJERGNG', 'N', 'C_Ergon' FROM DUAL
) TEMP_20160823154707
WHERE (SIS,GRUPO) NOT IN
  (SELECT SIS,GRUPO FROM GRUPO_ROTINAS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE GRUPO_ROTINAS ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE ROTINAS DISABLE ALL TRIGGERS')
INSERT INTO ROTINAS
(ARQUIVO, DESCRICAO, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, GRUPO, INIBE_ACIONAMENTO, LOGGING, ROTINA, SIS, TIPO)
SELECT * FROM (
SELECT ARQUIVO,DESCRICAO,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,GRUPO,INIBE_ACIONAMENTO,LOGGING,ROTINA,SIS,TIPO FROM ROTINAS WHERE 1=0 UNION ALL
SELECT 'C_ERG_ALTERAR_APOS', 'Rotina para efetuar alterações no registro de aposentadoria', '', '', '', '', '', '', '', '', '', '', 'RJERGNG', 'N', 'N', 'Altera aposentadoria Custom', 'C_Ergon', 'B' FROM DUAL
) TEMP_20160823154723
WHERE (GRUPO,SIS,ROTINA) NOT IN
  (SELECT GRUPO,SIS,ROTINA FROM ROTINAS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE ROTINAS ENABLE ALL TRIGGERS')
SET SCAN ON
