SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_MULT_EPS DISABLE ALL TRIGGERS')
INSERT INTO HAD_CAD_MULT_EPS
(AUDITAR, EP, EXEC, ORDEM, SINTAXE, SPROC)
SELECT * FROM (
SELECT AUDITAR,EP,EXEC,ORDEM,SINTAXE,SPROC FROM HAD_CAD_MULT_EPS WHERE 1=0 UNION ALL
SELECT 'N', 'TGRJ_EPA__EVENTO_FUNC_02', 'S', TO_NUMBER('3'), 'BEGIN'||CHR(10)||' IF TGRJ_EPA__EVENTO_FUNC_02(PCK_EVENTO_FUNC.P_EVENTO_FUNC(:1),PCK_EVENTO_FUNC.P_EVENTO_FUNC_OLD(:1),:2=''S'',:3=''S'',:4=''S'',:5) THEN '||CHR(10)||'   :6 := ''S'';'||CHR(10)||' ELSE '||CHR(10)||'   :6 := ''N''; '||CHR(10)||' END IF;'||CHR(10)||'END;', 'EPA__EVENTO_FUNC' FROM DUAL
) TEMP_20171122152202
WHERE (SPROC,EP) NOT IN
  (SELECT SPROC,EP FROM HAD_CAD_MULT_EPS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_MULT_EPS ENABLE ALL TRIGGERS')
SET SCAN ON
