SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_SPROC DISABLE ALL TRIGGERS')
INSERT INTO HAD_CAD_SPROC
(AUDITAR, EXEC, EXEC_MULT_EPS, SINTAXE, SPROC, TIPO)
SELECT * FROM (
SELECT AUDITAR,EXEC,EXEC_MULT_EPS,SINTAXE,SPROC,TIPO FROM HAD_CAD_SPROC WHERE 1=0 UNION ALL
SELECT 'N', 'N', 'S', 'BEGIN'||CHR(10)||' IF EPB__INSCRITOS(PCK_INSCRITOS.V_ROW_NEW,PCK_INSCRITOS.V_ROW_OLD,:1=''S'',:2=''S'',:3=''S'',:4) THEN :5 := ''S'';'||CHR(10)||' ELSE :5 := ''N''; END IF;'||CHR(10)||'END;', 'EPB__INSCRITOS', 'EPB' FROM DUAL
) TEMP_20170822082531
WHERE (SPROC) NOT IN
  (SELECT SPROC FROM HAD_CAD_SPROC)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_SPROC ENABLE ALL TRIGGERS')
SET SCAN ON

-----

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_MULT_EPS DISABLE ALL TRIGGERS')
INSERT INTO HAD_CAD_MULT_EPS
(AUDITAR, EP, EXEC, ORDEM, SINTAXE, SPROC)
SELECT * FROM (
SELECT AUDITAR,EP,EXEC,ORDEM,SINTAXE,SPROC FROM HAD_CAD_MULT_EPS WHERE 1=0 UNION ALL
SELECT 'N', 'TGRJ_EPB__INSCRITOS', 'S', TO_NUMBER('2'), 'BEGIN'||CHR(10)||' IF TGRJ_EPB__INSCRITOS(PCK_INSCRITOS.V_ROW_NEW,PCK_INSCRITOS.V_ROW_OLD,:1=''S'',:2=''S'',:3=''S'',:4) THEN '||CHR(10)||'   :5 := ''S'';'||CHR(10)||' ELSE '||CHR(10)||'   :5 := ''N''; '||CHR(10)||' END IF;'||CHR(10)||'END;', 'EPB__INSCRITOS' FROM DUAL
) TEMP_20170822082817
WHERE (SPROC,EP) NOT IN
  (SELECT SPROC,EP FROM HAD_CAD_MULT_EPS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_MULT_EPS ENABLE ALL TRIGGERS')
SET SCAN ON