SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_SPROC DISABLE ALL TRIGGERS')
INSERT INTO HAD_CAD_SPROC
(AUDITAR, EXEC, EXEC_MULT_EPS, SINTAXE, SPROC, TIPO)
SELECT * FROM (
SELECT AUDITAR,EXEC,EXEC_MULT_EPS,SINTAXE,SPROC,TIPO FROM HAD_CAD_SPROC WHERE 1=0 UNION ALL
SELECT 'N', 'N', 'S', 'BEGIN'||CHR(10)||' IF EPA__REGRAS_PENSAO_AL(PCK_REGRAS_PENSAO_AL.P_REGRAS_PENSAO_AL(:1),PCK_REGRAS_PENSAO_AL.P_REGRAS_PENSAO_AL_OLD(:1),:2=''S'',:3=''S'',:4=''S'',:5) THEN :6 := ''S'';'||CHR(10)||' ELSE :6 := ''N''; END IF;'||CHR(10)||'END;', 'EPA__REGRAS_PENSAO_AL', 'EPA' FROM DUAL
) TEMP_20160916134115
WHERE (SPROC) NOT IN
  (SELECT SPROC FROM HAD_CAD_SPROC)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_SPROC ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_MULT_EPS DISABLE ALL TRIGGERS')
INSERT INTO HAD_CAD_MULT_EPS
(AUDITAR, EP, EXEC, ORDEM, SINTAXE, SPROC)
SELECT * FROM (
SELECT AUDITAR,EP,EXEC,ORDEM,SINTAXE,SPROC FROM HAD_CAD_MULT_EPS WHERE 1=0 UNION ALL
SELECT 'N', 'TTGRJ_EPA__REGRAS_PENSAO_AL', 'S', TO_NUMBER('1'), 'BEGIN'||CHR(10)||' IF TTGRJ_EPA__REGRAS_PENSAO_AL(PCK_REGRAS_PENSAO_AL.P_REGRAS_PENSAO_AL(:1),PCK_REGRAS_PENSAO_AL.P_REGRAS_PENSAO_AL_OLD(:1),:2=''S'',:3=''S'',:4=''S'',:5) THEN '||CHR(10)||'   :6 := ''S'';'||CHR(10)||' ELSE '||CHR(10)||'   :6 := ''N''; '||CHR(10)||' END IF;'||CHR(10)||'END;', 'EPA__REGRAS_PENSAO_AL' FROM DUAL
) TEMP_20160916134140
WHERE (SPROC,EP) NOT IN
  (SELECT SPROC,EP FROM HAD_CAD_MULT_EPS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_CAD_MULT_EPS ENABLE ALL TRIGGERS')
SET SCAN ON
