SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE ROTINAS DISABLE ALL TRIGGERS')
INSERT INTO ROTINAS
(ARQUIVO, DESCRICAO, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, GRUPO, INIBE_ACIONAMENTO, LOGGING, ROTINA, SIS, TIPO)
SELECT * FROM (
SELECT ARQUIVO,DESCRICAO,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,GRUPO,INIBE_ACIONAMENTO,LOGGING,ROTINA,SIS,TIPO FROM ROTINAS WHERE 1=0 UNION ALL
SELECT 'TGRJ_PROCESSA_OBITO', 'Realiza atualização nas tabelas Funcionarios e TGRJ_SISOBI_REL inserindo informações referente a óbito', '', '', '', '', '', '', '', '', '', '', 'RJERGNG', 'N', 'N', 'Processa Óbito', 'C_Ergon', 'B' FROM DUAL
) TEMP_20170803150253
WHERE (GRUPO,SIS,ROTINA) NOT IN
  (SELECT GRUPO,SIS,ROTINA FROM ROTINAS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE ROTINAS ENABLE ALL TRIGGERS')
SET SCAN ON
-----
-- Parâmetros da Rotina
-----
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE PARAMETROS_ROTINAS DISABLE ALL TRIGGERS')
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_DATA_OBITO', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('2'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('7'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_NUM_CARTORIO', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('3'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('5'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_NUM_REGISTRO', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('4'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('5'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_NUM_REGISTRO_OBITO', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('5'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('5'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_FALECIMENTO', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('6'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('5'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_MOTIVO', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('7'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('5'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_CPF', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('8'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('5'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT 'P_NUMFUNC', '', 'P_NUMFUNC', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('1'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('6'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
INSERT INTO PARAMETROS_ROTINAS
(COL_DESC, COL_VALOR, DESCRICAO, GRUPO, NOMES_COLUNAS, ROTINA, SEQ, SIS, SQL_TEXTO, TAMANHO, TIPO, VALOR)
SELECT * FROM (
SELECT COL_DESC,COL_VALOR,DESCRICAO,GRUPO,NOMES_COLUNAS,ROTINA,SEQ,SIS,SQL_TEXTO,TAMANHO,TIPO,VALOR FROM PARAMETROS_ROTINAS WHERE 1=0 UNION ALL
SELECT '', '', 'P_REFPROC', 'RJERGNG', '', 'Processa Óbito', TO_NUMBER('9'), 'C_Ergon', '', TO_NUMBER(''), TO_NUMBER('5'), '' FROM DUAL
) TEMP_20171108122204
WHERE (ROTINA,SIS,GRUPO,SEQ) NOT IN
  (SELECT ROTINA,SIS,GRUPO,SEQ FROM PARAMETROS_ROTINAS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE PARAMETROS_ROTINAS ENABLE ALL TRIGGERS')
SET SCAN ON