SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE ROTINAS DISABLE ALL TRIGGERS')
INSERT INTO ROTINAS
(ARQUIVO, DESCRICAO, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, GRUPO, INIBE_ACIONAMENTO, LOGGING, ROTINA, SIS, TIPO)
SELECT * FROM (
SELECT ARQUIVO,DESCRICAO,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,GRUPO,INIBE_ACIONAMENTO,LOGGING,ROTINA,SIS,TIPO FROM ROTINAS WHERE 1=0 UNION ALL
SELECT 'ttgrj_dml_rjadm00068_al', 'Realiza o cadastro ou atualização nas tabelas REGRAS_PENSAO_AL inserindo informações referente a pensão alimenticia especial', '', '', '', '', '', '', '', '', '', '', 'RJERGNG', 'N', 'N', 'Pensão Alimenticia Especial', 'C_Ergon', 'B' FROM DUAL
) TEMP_20170803150253
WHERE (GRUPO,SIS,ROTINA) NOT IN
  (SELECT GRUPO,SIS,ROTINA FROM ROTINAS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE ROTINAS ENABLE ALL TRIGGERS')
SET SCAN ON
/