SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE TABELA DISABLE ALL TRIGGERS')
INSERT INTO TABELA
(DESCR, MULTI_EMP, SIS, TAB, TAMINFO, TAMINFO1, TAMINFO2, TAMINFO3, TIPO, TIPO1, TIPO2)
SELECT * FROM (
SELECT DESCR,MULTI_EMP,SIS,TAB,TAMINFO,TAMINFO1,TAMINFO2,TAMINFO3,TIPO,TIPO1,TIPO2 FROM TABELA WHERE 1=0 UNION ALL
SELECT 'Tipos de Auditoria', 'N', 'C_Ergon', 'PGOV_TP_AUDITORIA', TO_NUMBER('30'), TO_NUMBER('1'), TO_NUMBER('1'), TO_NUMBER(''), 'A', 'A', 'A' FROM DUAL
) TEMP_20170925171850
WHERE (TAB) NOT IN
  (SELECT TAB FROM TABELA)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE TABELA ENABLE ALL TRIGGERS')
SET SCAN ON
-----
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE ITEMTABELA_ DISABLE ALL TRIGGERS')
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Atributos/Lanç. Manual', 'Com_PAG', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Dependentes', 'Com_DEP', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Eventos', 'Com_CAD', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Benefícios', 'Com_BENEF', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Operador', 'Operador', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Individual', 'Individual', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Vínculos/Exercícios', 'Com_VINC', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Pensionistas', 'Com_PENS', 'S', 'S', 'PGOV_TP_AUDITORIA' FROM DUAL
) TEMP_20170925154852
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE ITEMTABELA_ ENABLE ALL TRIGGERS')
SET SCAN ON
