SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE TABELA DISABLE ALL TRIGGERS')
INSERT INTO TABELA
(DESCR, MULTI_EMP, SIS, TAB, TAMINFO, TAMINFO1, TAMINFO2, TAMINFO3, TIPO, TIPO1, TIPO2)
SELECT * FROM (
SELECT DESCR,MULTI_EMP,SIS,TAB,TAMINFO,TAMINFO1,TAMINFO2,TAMINFO3,TIPO,TIPO1,TIPO2 FROM TABELA WHERE 1=0 UNION ALL
SELECT 'Tabela com os tipos de cursos', 'N', 'C_Ergon', 'GOVRJ_TIPO_CURSOS', TO_NUMBER('30'), TO_NUMBER('30'), TO_NUMBER('30'), TO_NUMBER('30'), 'A', 'A', 'A' FROM DUAL
) TEMP_20160829140647
WHERE (TAB) NOT IN
  (SELECT TAB FROM TABELA)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE TABELA ENABLE ALL TRIGGERS')
SET SCAN ON
