SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE TABELA DISABLE ALL TRIGGERS')
INSERT INTO TABELA
(DESCR, MULTI_EMP, SIS, TAB, TAMINFO, TAMINFO1, TAMINFO2, TAMINFO3, TIPO, TIPO1, TIPO2)
SELECT * FROM (
SELECT DESCR,MULTI_EMP,SIS,TAB,TAMINFO,TAMINFO1,TAMINFO2,TAMINFO3,TIPO,TIPO1,TIPO2 FROM TABELA WHERE 1=0 UNION ALL
SELECT 'Transações de Auditoria de Comando', 'N', 'C_Ergon', 'PGOV_AUDITORIA_NIV1', TO_NUMBER('50'), TO_NUMBER('20'), TO_NUMBER('10'), TO_NUMBER(''), 'A', 'A', 'A' FROM DUAL
) TEMP_20170921112925
WHERE (TAB) NOT IN
  (SELECT TAB FROM TABELA)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE TABELA ENABLE ALL TRIGGERS')
SET SCAN ON
-----
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE ITEMTABELA_ DISABLE ALL TRIGGERS')
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Aposentadoria Temporal', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Aquisição Licença Especial', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Atributos de Dependentes', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Atributos de Funcionários', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Atributos de Pensionistas', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Averbações', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Cadastro de Funcionários para Atributo', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Carga de Atributos Customizada', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Cessões', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Cessões Internas', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Dados Gerais', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Disposição Interna', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Eventos de Cargo', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Eventos de Enquadramento', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Eventos de Mudança de Cargo', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Eventos de Progressão', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Eventos de Remoção', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Exercícios/ Funcionário', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Freqüência', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Funcionários', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Incorporação de Chefia', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Ingresso', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Instituidor de Pensão', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Lançamento Manual', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Lançamento Manual Pensionista', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Licenças Especiais', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Pensionista Previdenciário', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Pensionistas', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Pensões Alimentícias', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Pré-Contagem', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Regra de Bloqueio ou Repasse', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Regras de Pensão Especial', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Regras de Pensão Previdenciária', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Requisição', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Vacância', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'Vínculo', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Aposentadorias e reversões', 'ERGadm00230', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Aquisição de licenças especiais', 'ERGadm00254', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Atributos do dependente', 'ERGadm00300', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Atributos do funcionário', 'ERGadm00199', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Atributos do pensionista', 'ERGadm00301', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Averbações de tempo', 'ERGadm00262', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Eventos de cargo', 'ERGadm00156', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Eventos de mudança de cargo', 'ERGadm00157', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Eventos de mudança de jornada', 'ERGadm00160', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Eventos de progressão', 'ERGadm00158', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Eventos de remoção', 'ERGadm00159', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Eventos de substituição', 'ERGadm00165', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Movimentos do pensionista', 'ERGadm00143', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Movimentos retroativos do pensionista', 'ERGadm00145', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Pensionistas', 'ERGadm00237', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Pensionista Previdenciário', 'RJadm00039', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Dependentes do pensionista', 'ERGadm00468', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Dados Gerais MS605', 'RJadm00067', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Regras de pensão especial', 'ERGadm00203', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Regras de Pensão MS605', 'RJadm00068', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Regras de Pensão Previdenciária', 'RJadm00040', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Vínculos funcionais', 'ERGadm00229', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Cessões internas', 'ERGadm00188', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Atividades e exercícios do funcionário', 'ERGadm00186', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Movimentos de funcionários', 'ERGadm00142', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Movimentos retroativos por funcionário', 'ERGadm00479', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Movimentos retroativos por funcionário', 'ERGadm00144', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Frequências', 'ERGadm00189', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Lançamento coletivo de frequências', 'ERGadm00243', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Pré-contagem', 'ERGadm00162', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Licenças especiais', 'ERGadm00152', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Dependências do dependente', 'ERGadm00224', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Dependentes do funcionário', 'ERGadm00217', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT 'Regras de pensão alimentícia do funcionário', 'ERGadm00146', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
INSERT INTO ITEMTABELA_
(DESCR, ITEM, ITEM1, ITEM2, TAB)
SELECT * FROM (
SELECT DESCR,ITEM,ITEM1,ITEM2,TAB FROM ITEMTABELA_ WHERE 1=0 UNION ALL
SELECT '', 'ERGadm00187', '', '', 'PGOV_AUDITORIA_NIV1' FROM DUAL
) TEMP_20170921113219
WHERE (TAB,ITEM) NOT IN
  (SELECT TAB,ITEM FROM ITEMTABELA_)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE ITEMTABELA_ ENABLE ALL TRIGGERS')
SET SCAN ON