CREATE OR REPLACE FORCE 
VIEW RJADM00045_PARAMETROS_ATRIB 
AS 
  SELECT P.VANTAGEM
        ,(SELECT T.VANTAGEM ||' - '|| T.NOME VANTAGEM_DESCR FROM TIPO_VANTAGEM_ T WHERE T.VANTAGEM = P.VANTAGEM) VANTAGEM_DESCR
        ,P.DTFIM        
        ,P.INFO         
        ,P.OBS          
        ,P.INFO2        
        ,P.LANC_UNICO   
        ,P.INFO4        
        ,P.INFO5 
        ,ROWIDTOCHAR(P.ROWID) ROWID_REG
  FROM PGOV_PARAM_ATRIBUTO P
/