CREATE OR REPLACE VIEW RJADM00005_DISCIP_CARGO
AS 
  SELECT CARGO,
         NOMECARGO,
         CATEGORIA,
         SUBCATEGORIA,
         COD_DISCIPLINA,
         CARGO || ' - ' || NOMECARGO DESCR_CARGO,
         ROWIDTOCHAR(ROWID) ROWID_REG
  FROM RH_DISCIP_CARGO DP;
/