CREATE OR REPLACE FORCE VIEW TTGRJ_RJADM00060_INDICE_REFER
AS 
    SELECT R.ID_INDICE_REFER, 
           R.DATA_REFERENCIA,
           R.OBSERVACAO,
           rowidtochar(R.ROWID) ROWID_REG
      FROM TGRJ_INDICE_REFER R
/