CREATE OR REPLACE
PROCEDURE TTGRJ_PRC_VALORES_COMPL_ASYNC (p_rubrica  IN NUMBER, V_MENS OUT VARCHAR2)  
AS PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
  PRC_VALORES_COMPLEMENTO(NULL, NULL, NULL, NULL, p_rubrica, TRUNC(SYSDATE), TRUNC(SYSDATE), V_MENS);
  COMMIT;
  RETURN;
END;
/