CREATE OR REPLACE VIEW TTGRJ_RJADM00051_VW_CORRELATAS ("DESCRICAO", "DISCIPLINA_CORRELATA", "DISCIPLINA", "CHAVE", "ROWID_REG") AS 
  SELECT D.DESCRICAO, DC.DISCIPLINA_CORRELATA, DC.DISCIPLINA, DC.CHAVE, ROWIDTOCHAR(D.ROWID) AS ROWID_REG FROM RH_DISCIPLINAS D
JOIN TGRJ_DISCI_CORRELATAS DC
ON D.DISCIPLINA = DC.DISCIPLINA_CORRELATA;
/