--- RJadm 00053 28/07/2017 Arnaldo
CREATE OR REPLACE FORCE 
VIEW TTGRJ_RJADM00053_TP_BF_DOCUMEN AS
SELECT t.TIPO,
		t.TIPODOC,
		t.TIPODOC || ' - ' || (SELECT DESCRICAO FROM ERG_LEI_TIPO l WHERE ABRANGENCIA = 'PENSAO PREVID' AND TIPODOC = t.TIPODOC) AS TIPODOC_DESC,
		t.FL_OBRIGATORIO,
		rowidtochar(rowid) as ROWID_REG 
FROM TGRJ_TIPO_BENEF_DOCUMENTO t
ORDER BY 2
/