CREATE OR REPLACE FORCE VIEW TTGRJ_RJADM00060_INDIC_PENSPRV
AS 
    SELECT R.ID_INDICE_REFER, 
           R.ANO_SUBSEQUENTE,
           R.INDICE_CORRECAO,
           rowidtochar(R.ROWID) ROWID_REG
      FROM TGRJ_INDICE_PENSPREV R
/