BEGIN
  EXECUTE IMMEDIATE 'drop type UTIL_TYP_ITEMTABELA_TAB';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

CREATE OR REPLACE TYPE UTIL_TYP_ITEMTABELA AS OBJECT (
DESCR VARCHAR2(180),
ITEM1 VARCHAR2(99),
ITEM2 VARCHAR2(99),
ITEM3 CLOB)
/

CREATE OR REPLACE TYPE UTIL_TYP_ITEMTABELA_TAB
AS TABLE OF UTIL_TYP_ITEMTABELA
/

